swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/account:
    post:
      tags:
        - Account Module
      summary: Account
      description: API for fetching user account
      security:
        - Bearer: []
      responses:
        '200':
          description: Account retrieved successfully
          schema:
            $ref: '#/definitions/AccountResponse'
        '401':
          description: Unauthorized user
        '500':
          description: Internal Server Error
  /account/{accountID}/transactions:
    post:
      tags:
        - Account and Transactions Module
      summary: Account transactions
      description: List of transactions associated with an account
      security:
        - Bearer: []
      parameters:
        - in: path
          name: accountID
          description: ID of an account
          required: true
          type: string
      responses:
        '200':
          description: All transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/TransactionsResponse'
        '401':
          description: Unauthorized user
        '404':
          description: Account not found
        '500':
          description: Internal Server Error
  /transactions/{transactionID}/category/{categoryID}:
    put:
      tags:
        - Account and Transactions Module
      summary: Edit transaction's category
      description: Editing a category of a transaction
      security:
        - Bearer: []
      parameters:
        - in: path
          name: transactionID
          description: ID of a transaction
          required: true
          type: string
        - in: path
          name: categoryID
          description: ID of a category
          required: true
          type: string
        - in: body
          name: category
          description: Modify transaction's category
          required: true
          schema:
            $ref: '#/definitions/TransactionCategory'
      responses:
        '200':
          description: Category modified successfully
          schema:
            $ref: '#/definitions/TransactionResponseNote'
        '401':
          description: Unauthorized user
        '404':
          description: Category not modified
        '500':
          description: Internal Server Error
  /transactions/{transactionID}/note:
    post:
      tags:
        - Account and Transactions Module
      summary: Add transaction's note
      description: API for adding a note to a transaction
      security:
        - Bearer: []
      parameters:
        - in: path
          name: transactionID
          description: ID of a transaction
          required: true
          type: string
        - in: body
          name: note
          description: New transaction's note
          required: true
          schema:
            $ref: '#/definitions/TransactionNote'
      responses:
        '200':
          description: Note added to the transaction successfully
          schema:
            $ref: '#/definitions/TransactionResponseNote'
        '401':
          description: Unauthorized user
        '404':
          description: Note not created
        '500':
          description: Internal Server Error
  /transactions/{transactionID}/note/{noteID}:
    put:
      tags:
        - Account and Transactions Module
      summary: Edit transaction's note
      description: Editing a note of a transaction
      security:
        - Bearer: []
      parameters:
        - in: path
          name: transactionID
          description: ID of a transaction
          required: true
          type: string
        - in: path
          name: noteID
          description: ID of a note
          required: true
          type: string
        - in: body
          name: note
          description: Modify transaction's note
          required: true
          schema:
            $ref: '#/definitions/TransactionNote'
      responses:
        '200':
          description: Note modified successfully
          schema:
            $ref: '#/definitions/TransactionResponseNote'
        '401':
          description: Unauthorized user
        '404':
          description: Note not modified
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  AccountResponse:
    type: object
    properties:
      accountID:
        type: string
        description: account ID
      accountName:
        type: string
        description: account name
      accountCurrency:
        type: string
        description: account currency
      currentBalance:
        type: number
        description: current account balance
        format: double
  TransactionsResponse:
    type: object
    properties:
      transactionID:
        type: string
        description: transaction ID
      transactionType:
        type: string
        description: type of transaction
      date:
        type: string
        format: date-time
        description: date of transaction
      description:
        type: string
        description: description of transaction
      amount:
        type: number
        description: transaction amount
      balance:
        type: number
        description: available balance
        format: double
      category:
        type: string
        description: name of the category
      note:
        type: string
        description: user note
  TransactionCategory:
    type: object
    properties:
      category:
        type: string
  TransactionNote:
    type: object
    properties:
      note:
        type: string
  TransactionResponseNote:
    type: object
    properties:
      note:
        type: string
      noteID:
        type: string
