swagger: '2.0'
info:
  version: "1.0.0"
  title: "Bank Argent API documentation"
  description: "Contains all available API endpoints for managing transactions"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: "/api/v1"
schemes:
  - "http"
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /account/{accountID}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - "Transactions Module"
      summary: "Account transactions"
      description: "List of transactions associated with a bank's account"
      operationId: "getAccountTransactions"
      parameters:
        - name: "accountID"
          in: "path"
          description: "ID of an account"
          required: true
          type: "string"
      produces:
        - "application/json"
      responses:
        "200":
          description: "All transactions retrieved successfully"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TransactionsResponse"
        "401":
          description: "Unauthorized user"
        "404":
          description: "Account not found"
        "500":
          description: "Internal Server Error"
  /transactions/{transactionID}:
    get:
      security:
        - Bearer: []
      tags:
        - "Transactions Module"
      summary: "Transaction by ID"
      description: "Find one transaction"
      operationId: "TransactionByID"
      parameters:
        - name: "transactionID"
          in: "path"
          description: "ID of a transaction"
          required: true
          type: "string"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Transaction retrieved successfully"
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "401":
          description: "Unauthorized user"
        "404":
          description: "Transaction not found"
        "500":
          description: "Internal Server Error"
    put:
      security:
        - Bearer: []
      tags:
        - "Transactions Module"
      summary: "Edit transaction"
      description: "Editing a transaction's category/note"
      operationId: "EditTransaction"
      parameters:
        - name: "transactionID"
          in: "path"
          description: "ID of a transaction"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "Modify transaction"
          required: true
          schema:
            $ref: "#/definitions/EditTransactionResponse"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Transaction modified successfully"
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "401":
          description: "Unauthorized user"
        "404":
          description: "Note not modified"
        "500":
          description: "Internal Server Error"
definitions:
  TransactionsResponse:
    type: "object"
    properties:
      transactionID:
        type: "string"
        description: "transaction ID"
      userID:
        type: "string"
        description: "user ID"
      date:
        type: "string"
        format: "date-time"
        description: "date of transaction"
      description:
        type: "string"
        description: "description of transaction"
      amount:
        type: "number"
        description: "transaction amount"
      balance:
        type: "number"
        description: "available balance"
        format: "double"
      transactionType:
        type: "string"
        description: "type of transaction"
      category:
        type: "string"
        description: "name of the category"
      note:
        type: "string"
        description: "user note"
  EditTransactionResponse:
    type: "object"
    properties:
      category:
        type: "string"
        description: "name of the category"
      note:
        type: "string"
        description: "user note"

